name = "FittingFunction"
uuid = "7c8a6357-aefd-4570-aae0-a8cd991d38f9"
authors = ["Stefano Covino <stefano.covino@inaf.it> and contributors"]
version = "0.11.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DustExtinction = "fb44c06c-c62f-5397-83f5-69249e0a3c8e"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
CSV = "0.10"
DataFrames = "1"
DustExtinction = "0.11"
PhysicalConstants = "0.2"
Unitful = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
