name = "FittingFunction"
uuid = "7c8a6357-aefd-4570-aae0-a8cd991d38f9"
authors = ["Stefano Covino <stefano.covino@inaf.it> and contributors"]
version = "0.1.3"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
