name = "FittingFunction"
uuid = "7c8a6357-aefd-4570-aae0-a8cd991d38f9"
authors = ["Stefano Covino <stefano.covino@inaf.it> and contributors"]
version = "0.3.0"

[deps]
DustExtinction = "fb44c06c-c62f-5397-83f5-69249e0a3c8e"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
